### ISSUE TITLE
Add Sample app

### ISSUE THREAD

**Issue by c-arnab** [MultiTenancyServer/MultiTenancyServer#1]
It would be great if a sample app was provided.
The app could be just a single form and report where data is added in a form and showed back in a tabular report structure with all user data of a specific tenant shown.
The parser can be a simple child path parser.

This would also be useful as we can understand the necessary db structure to create for custom app.

Best Regards

**Comment by krispenner** [comment]
@c-arnab yes this was on my to-do list!

**Sample project**
https://github.com/MultiTenancyServer/MultiTenancyServer.Samples/tree/master/src/AspNetIdentityAndEFCore

**Diff of commit for adding multi-tenancy support**
https://github.com/MultiTenancyServer/MultiTenancyServer.Samples/commit/0dabd345473d64a58b5ccf72cd8de6766d0b7969#diff-5402c86148335f8194c6a85d5fffe6dd

_Please note I found an issue with the PathParser so please get latest if you are using that._

**Comment by krispenner** [comment]
I am closing this as there are now several samples provided in the [samples repo](https://github.com/MultiTenancyServer/MultiTenancyServer.Samples).
