### ISSUE TITLE
Enforced global query filters

### ISSUE THREAD

**Issue by filipecarneiro** [MultiTenancyServer/MultiTenancyServer#11]
Hi Kris,

Sorry if I’m making too much questions in a “issue” list. I have the feeling that I’m abusing… 😊

I have a scenario with an entity, say “tasks” should be tenanted. I mean, only the owner tenant should make CRUD operations on those.

But, I also have an API (different controller) where I want to retrieve a single task for anonymous users. And, for that, I have a different authorization mechanism and will make a query without tenant context and provide only the task id.

How can I make that specific query to not filter by tenant id? Is there a mechanism to disable/enable the enforced global query filters? Any other way?

One note: I don’t know the tenant of that task, just the task id. Otherwise I guess that I could just change the context tenant to that and remove-it right after.

Thank you,

**Comment by filipecarneiro** [comment]
"Filters may be disabled for individual LINQ queries by using the IgnoreQueryFilters() operator." :)

https://docs.microsoft.com/en-us/ef/core/querying/filters

**Comment by krispenner** [comment]
@filipecarneiro 

Other options:

You could create a 'system' tenant to hold your system level tasks.

You could use `NullTenantReferenceHandling.NullableEntityAccess` where a null tenant refers to the 'system' tenant.

You could use `NullTenantReferenceHandling.NotNullGlobalAccess` where a null tenant queries across all tenants.

```
public enum NullTenantReferenceHandling
{
    // Summary:
    //     A null tenant reference is NOT allowed for the entity, where possible a NOT NULL
    //     or REQUIRED constraint should be set on the tenant reference, querying for entities
    //     with a null tenant reference will match NO entities.
    //     This is the default option.
    NotNullDenyAccess = 0,

    // Summary:
    //     A null tenant reference is allowed for the entity, where possible an NULLABLE
    //     or OPTIONAL constraint should be set on the tenant reference, querying for entities
    //     with a null tenant reference will match those expected results.
    //     This may be useful where globally defined system entities are set with a null
    //     tenant reference.
    NullableEntityAccess = 1,

    // Summary:
    //     A null tenant reference is NOT allowed for the entity, where possible a NOT NULL
    //     or REQUIRED constraint should be set on the tenant reference, querying for entities
    //     with a null tenant reference will match ALL entities across all tenants.
    //     For obvious security reasons, this is typically not recommended; however, this
    //     can be useful for admin reporting across all tenants.
    NotNullGlobalAccess = 2
}
```
