### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ksjdesign** [MultiTenancyServer/MultiTenancyServer#12]
Hello - i'm testing this package and find the implementation simple and easy going compared to other packages i've tested. Keep up the good if not even great work :)

Question:

I get a "NullReferenceException: Object reference not set to an instance of an object", when doing the query:

`return _dbContext.TenantcyTestEntities.Select(x=> x).ToList();`

The TenantcyTestEntity modelbuilder setup:

```
modelBuilder.Entity<TenantcyTestEntity>(b =>
            {
                b.Property(t => t.Text).HasMaxLength(256);

                // Add multi-tenancy support to entity.
                b.HasTenancy(() => _tenancyContext.Tenant.Id, _tenancyModelState, hasIndex: false);
            });
```

The NullTenantReferenceHandling is set to default: `NullTenantReferenceHandling.NotNullDenyAccess`.

As far as i can see - it's because i'm trying to get the list the TenantcyTestEntity and my _tenancyContext.Tenant is null. Therefore it has no id, and the lambda expression in TenancyEFExtensions cannot work when _tenancyContext.Tenant is null?

This kills the expression and return null, then when trying to "ToList()" - i get the NullReferenceException.

I would think i should return an empty list, not null?

**Comment by krispenner** [comment]
Hi @ksjdesign sorry for the delay. Can you provide details on your setup?
Are you targeting .NET Framework or .NET Core? 2.x or 3.x?
What version of the MultiTenancyServer packages are you using?

FYI, you need to use the latest beta version of MultiTenancyServer for .NET Core 3.x to work and it hasn't been fully tested.
