### ISSUE TITLE
AddChildPathParser

### ISSUE THREAD

**Issue by ksjdesign** [MultiTenancyServer/MultiTenancyServer#13]
I can't seen to get the ".AddChildPathParser("/tenants/")" to work.

When running my site on the url: https://localhost:44301/tenants/tenant1, no tenant is found / selected?

A'm i missing something?

Also tried:
.AddPathParser("^/tenants/([a-z0-9]+)(?:[/]?)$")

Not working either.

Also the 2 samples for "Identity Server 4" and "Database per tenant" is missing.
I don't currently need them - just letting you know :)

**Comment by krispenner** [comment]
Hi @ksjdesign I would need a lot more details on your configuration. Please post your entire Startup.cs file, that should be a good start.

> Also the 2 samples for "Identity Server 4" and "Database per tenant" is missing.

You can find them in the v1 branch, they were not brought over into the master branch yet as it's being reworked for .NET Core 3.x and they require changes which I haven't gotten to yet.

**Comment by kiranvsr** [comment]
I am just trying out this today to use in my application and see the same issue. Below are the steps.
1. Setup child path parser
2. update launch settings to change applicationurl to basepath
3. debug
4. login in the website
5. No tenant found error (NullReferenceException error)

I haven't gone into the code yet, but I think the parser could not find the child path in the URL. A custom URL + route combination will fix this.

I have a question - do the other parsers (Ex. Header, claims, etc) append the tenant details on first login?

============ Exception details ================
NullReferenceException: Object reference not set to an instance of an object.
lambda_method(Closure , QueryContext )
Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync<TResult>(Expression query, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync<TResult>(Expression expression, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync<TSource, TResult>(MethodInfo operatorMethodInfo, IQueryable<TSource> source, Expression expression, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync<TSource, TResult>(MethodInfo operatorMethodInfo, IQueryable<TSource> source, LambdaExpression expression, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.FirstOrDefaultAsync<TSource>(IQueryable<TSource> source, Expression<Func<TSource, bool>> predicate, CancellationToken cancellationToken)
Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserOnlyStore<TUser, TContext, TKey, TUserClaim, TUserLogin, TUserToken>.FindByNameAsync(string normalizedUserName, CancellationToken cancellationToken)
Microsoft.AspNetCore.Identity.UserManager<TUser>.FindByNameAsync(string userName)
Microsoft.AspNetCore.Identity.SignInManager<TUser>.PasswordSignInAsync(string userName, string password, bool isPersistent, bool lockoutOnFailure)
Microsoft.AspNetCore.Identity.UI.V4.Pages.Account.Internal.LoginModel<TUser>.OnPostAsync(string returnUrl)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory+GenericTaskHandlerMethod.Convert<T>(object taskAsObject)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory+GenericTaskHandlerMethod.Execute(object receiver, object[] arguments)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
MultiTenancyServer.Hosting.TenancyMiddleware<TTenant>.InvokeAsync(HttpContext httpContext, ITenancyContext<TTenant> tenancyContext, ITenancyProvider<TTenant> tenancyProvider, ITenantStore<TTenant> tenantStore) in TenancyMiddleware.cs
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

==========

Thanks,
Kiran
