### ISSUE TITLE
MongoDb Support

### ISSUE THREAD

**Issue by hakeemoriola** [MultiTenancyServer/MultiTenancyServer#6]
Can I use this for MongoDb backend? I use ObjectId instead of Long but am stuck here

            services.AddMultiTenancy<ApplicationTenant, ObjectId>()
                .AddRequestParsers(parsers =>
                {
                    parsers.AddChildPathParser("/tenants/");
                });
            //.AddEntityFrameworkStore<IApplicationUserDbContext, ApplicationTenant, ObjectId>();
            services.ConfigureMongoDbIdentity<ApplicationUser, ApplicationRole, ObjectId>(mongoDbIdentityConfiguration);

**Comment by krispenner** [comment]
I’m not familiar with MongoDb myself. You would need to implement the IQueryableTenantStore to read/write tenants from/to MongoDb unless you used some other implementation to store your tenants. 

Other than that it should work I would assume. Are you able to fork one of the sample projects and convert it to MongoDb with the minimum number of changes and then let me see what you have?

**Comment by hakeemoriola** [comment]
I have added you as a contributor to the project you can review the projects what am doing wrong I appreciate the help.
Thanks

**Comment by hakeemoriola** [comment]
https://github.com/hakeemoriola/MultiTenancyServer.MongoDb

**Comment by krispenner** [comment]
Try changing your startup code to this:

```cs
            // Add Multi-Tenancy services.
            services.AddMultiTenancy<ApplicationTenant, ObjectId>()
                .AddRequestParsers(parsers =>
                {
                    // To test a domain parser locally, add a similar line 
                    // to your hosts file for each tenant you want to test
                    // For Windows: C:\Windows\System32\drivers\etc\hosts
                    // 127.0.0.1    tenant1.tenants.local

                    parsers.AddSubdomainParser(".tenants.local");

                    //parsers.AddChildPathParser("/tenants/");
                })
                .AddInMemoryStore(new ApplicationTenant[]
                {
                    new ApplicationTenant()
                    {
                        Id = ObjectId.GenerateNewId(),
                        CanonicalName = "tenant1",
                        NormalizedCanonicalName = "TENANT1"
                    }
                });
```

Then add `127.0.0.1    tenant1.tenants.local` to your `C:\Windows\System32\drivers\etc\hosts` file.

Then test using http://tenant1.tenants.local/

Let me know if that works and if not what your issues are. You need to give more details.

**Comment by hakeemoriola** [comment]
System.ArgumentNullException: "Value cannot be null.\nParameter name: implementationFactory"
  at Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped[TService,TImplementation](IServiceCollection services, Func`2 implementationFactory)\n   at MultiTenancyServer.Configuration.DependencyInjection.TenancyBuilder`2.AddTenantStore[TStore](Func`2 storeFactory) in C:\\projects\\multitenancyserver\\src\\Core\\Configuration\\TenancyBuilder.cs:line 72\n   at Microsoft.Extensions.DependencyInjection.TenancyBuilderExtensions.AddInMemoryStore[TTenant,TKey](TenancyBuilder`2 builder, IEnumerable`1 tenants) in C:\\projects\\multitenancyserver\\src\\Stores\\TenancyBuilderExtensions.cs:line 29\n   at ApplicationHost.Startup.ConfigureServices(IServiceCollection services) in /Users/hakeemoriola/Documents/GitHub/infusync/infusync.identity/Startup.cs:line 155\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)\n   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()\n   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()\n   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()\n   at ApplicationHost.Program.Main(String[] args) in /Users/hakeemoriola/Documents/GitHub/infusync/infusync.identity/Program.cs:33

**Comment by krispenner** [comment]
Can you get latest and try again? It appears the factory parameter in the service registration is no longer optional after the upgrade from .NET Core 2.0 to 2.2. I have fixed this based on the error you reported but didn't have time to test it.

**Comment by hakeemoriola** [comment]
I have upgraded the library just as you suggested I could say it works based on the Log attached. and I made a few modifications on the code to make it work with MongoDB. the modification I will like to share with you if you don't mind.

if you can help review the log attached and point me if am in the right direction.

right now I can't log in to Identitityserver 


[Logs.txt](https://github.com/MultiTenancyServer/MultiTenancyServer/files/2983789/Logs.txt)

**Comment by krispenner** [comment]
You should use the domain parser as its much simpler to use.
`parsers.AddSubdomainParser(".tenants.local")`
Then you need to make sure you go to the URL that matches a tenant.

**Comment by hakeemoriola** [comment]
I noticed it's not persisting the Tenants I seeded. Added IEntityBase just for it to be compatible with the repository pattern I am using. 


public class ApplicationTenant : TenancyTenant<ObjectId>, IEntityBase<ObjectId> {
        public string DisplayName { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string CreatedBy { get; set; }
    }

**Comment by krispenner** [comment]
Yes that is because we are using the in-memory store. If you want persistence then you need to implement the ITenantStore yourself. The point of the in-memory store is for simple testing so you could ensure the tenancy context is set and working in your requests. If that’s working fine now, then you can implement ITenantStore with an MongoDB implementation.
