### ISSUE TITLE
Applying migrations

### ISSUE THREAD

**Issue by DavidDury** [MultiTenancyServer/MultiTenancyServer#7]
If we implement this into a SaaS solution, and will have let's say 1000 tenants, how can I update all databases when changes will come? Assuming there will be database changes for new functionalities etc and I need to apply the migrations to all 1000 tenants that each uses it's own database.

**Comment by krispenner** [comment]
You would still have a tenant management database or some other ITenantStore implementation that could retrieve all tenants and their connection strings whether it’s the whole connectionn string property on the tenant object or generate a generic connection string with their canonical name as part of their database name.

However this is something that in my view should be handled by your deployment mechanism. If your using Azure Pipelines in DevOps you could generate your SQL migration script during every build pipeline as an output SQL file and then have it executed against each database during the release pipeline that loops over each tenant database connection. I don’t believe the database should be updated by the application as the application should only have data read/write permissions and not be allowed to make schema changes.
