### ISSUE TITLE
Add template string as a domain parser parser parameter

### ISSUE THREAD

**Issue by dpoblacion** [MultiTenancyServer/MultiTenancyServer#8]
My service use the first domain segment for the tenant identifier.
For example:
http://**tenant1**.aaa.com
http://**tenant2**.bbb.com
After check your code, I have no idea how to get my tenant identifier with current parsers.

I think it will be interesting to have some template to define a domain strategy.
For example:
.AddDomainParser({tenant}.*) // first domain segment as identifier.
.AddDomainParser({tenant}.multitenancyserver.io) // subdomain for the tenant identifier with static main domain

This strategy is used by other libraries. Use request host value to determine the tenant with regular expressions, and maybe you could remove AddSubdomainParser and AddHostnameParser to keep things more simple

**Comment by krispenner** [comment]
Hi @dpoblacion,

You can easily extend this with your own custom parser class.

Or just use an inline lambda expression:
`.AddCustomParser(httpContext => httpContext.Request.Host.Host.Split('.')[0])`

Or just use an inline regular expression:
`.AddHostnameParser(@"^([a-z0-9-]+)(?:\..+$")`

I haven't tested either, just writing them out in here so you may need to tweak them.

**Comment by dpoblacion** [comment]
Custom parser works great. Thanks for your quick response.
