### ISSUE TITLE
Login without tenant identification

### ISSUE THREAD

**Issue by filipecarneiro** [MultiTenancyServer/MultiTenancyServer#9]
Thank you for your great work!

Your middleware is well organized, simple to use and powerful.

I’m using a subdomain parser for tenant identification and ASP.NET core identity in a study project.

I wonder what are your thoughts about login in the parent host domain. It would be nice to redirect the user to the correct subdomain but, for that, we would have to keep the unique index on NormalizedUserName (…that I think is acceptable).

Currrentlly, loging in in the parent domain, without tenant identification, throws an `NullReferenceException` at `MultiTenancyServer.Hosting.TenancyMiddleware`1.InvokeAsync(HttpContext httpContext, ITenancyContext`1 tenancyContext, ITenancyProvider`1 tenancyProvider, ITenantStore`1 tenantStore) in C:\projects\multitenancyserver-aspnetcore\src\AspNetCore\Hosting\TenancyMiddleware.cs:line 54`

Can you point me in the right direction for this feature?

Thanks,
Filipe

**Comment by krispenner** [comment]
Hi @filipecarneiro,

Were you able to resolve this? Let me know if it's still an issue and if so, if you are targeting ASP.NET 2.x or 3.x. Based on your other issue, it sounds like you may have go this one working or changed course to use UserClaims...

Off the top of my head I'm not sure what may be the issue, you can please supply some code to reproduce it.

Thanks.

**Comment by filipecarneiro** [comment]
I’m using ASP.NET Core 3.0 but, you are right, I’ve changed the course to use UserClaims.
And now, as it’s working well, I feel that I prefer to use user claims for identification and keep my host static.
Thank you, for all your great work!
